### PR TITLE
Deal with nested code tags

### PR DESCRIPTION
**Pull request by mamiefurax**
change the regexp in CodeHook in order to deal with nested code tags, see unit test for examples and understanding !

### CODE REVIEW

**Comment by milesj** [comment]
What is the use case for nested code tags?

**Comment by mamiefurax** [comment]
For example to show how to use bbcode code tag. I need to be able to do the following :
[code]
this is a sample usage of [code] bbcode tag  :
```
[code="php"]
<?php 
echo 'hello world';
?>
[/code]
you can use this tag to show some code to other people, you must specify the language used to allow syntax coloration
[/code]
```

And I need to see the following html :
```
<pre><code>
this is a sample usage of [code] bbcode tag  :
[code="php"]
<?php 
echo 'hello world';
?>
[/code]
you can use this tag to show some code to other people, you must specify the language used to allow syntax coloration
</code></pre>
```

and without the recursion in the regexp i have the following :
```
<pre><code>
this is a sample usage of [code] bbcode tag  :
[code="php"]
<?php 
echo 'hello world';
?>
</code></pre>
```

which is pretty wrong

**Comment by milesj** [comment]
Would of been nice if you submitted this pull yesterday before I tagged a new version :P
I'll get it in shortly.

**Comment by mamiefurax** [comment]
I've just discover this point today, sorry for the delay ;)

**Comment by milesj** [comment]
If you have any other suggestions/improvements, now would be a good time :P

**Pull request merged**
