### PR TITLE
Remove useless mb_strtolower on tags name when seeking tags attributes

### PR DESCRIPTION
**Pull request by mamiefurax**
I found this bug using a bbcode in camel case with attributes which was not defined.
It now work without the strtolower locally

### CODE REVIEW

**Comment by milesj** [comment]
Can you add a test case for this?

**Comment by mamiefurax** [comment]
I've just update the pull request with a test case showing this.
You can test that it will fail if you do the mb_strtolower in Decoda Class

**Comment by milesj** [comment]
Cool thanks!

**Comment by lgiraudel** [comment]
I think there's still an issue with the `parent` option of a tag.

**Comment by milesj** [comment]
I'll dig into it a bit more.

**Pull request merged**
