### PR TITLE
Use recommended PSR-4 autoload. PHP 5.6+

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/milesj/decoda/issues/146

- Moves non autoloadable files into their recommended structure/folders.
- PHP5.6+ as last PHP5 support version before going PHP7.2+

WIP for releasing.

missing:
- [ ] CS (array brackets)
- [x] PHP7.4+ confirmation

but this can be follow up PRs - so this PR can already be merged IMO.

### CODE REVIEW

**Comment by dereuromark** [comment]
I would recommend removing the version file in root.
It is only a source to forget to change for release - I don't think anyone needs it. So far composer now tells you easier what version you are having installed.
Is that OK for you? Then I would add this to this PR.

**Review by milesj — APPROVED** [review]

**Comment by alquerci** [comment]
Hello @dereuromark ,

A short comment to share my opinion about the versioning.

I see this bump to a minor version.

Removing a PHP version support should bring a new major version as it is a backward compatibility break.

However you done a good initiative by doing this stuff.

cc @milesj

**Comment by dereuromark** [comment]
I disagree with that reasoning. A minor is fine to remove versions that are long eol.
No bc issues, composer will just prevent from Pulling. So all fine.

**Comment by alquerci** [comment]
Yes, you're right.

**Pull request merged**
