### PR TITLE
Fix url path issue

### PR DESCRIPTION
**Pull request by vladrusu**
Also, a small change: added tilde (~) support and removed support for brackets ([]) in URL.
Why removing brackets?
Because they could lead in including in url adjacent BB code tags such as [b] a.s.o.
I don't think it's a big issue, imho.

### CODE REVIEW

**Comment by vladrusu** [comment]
Hello !
Any news?

**Comment by milesj** [comment]
Brackets are necessary for URLs like `foo[0]=123&foo[1]=456`.

**Comment by NimlothCQ** [comment]
Yes please... looking for this to get merged also :|

**Comment by milesj** [comment]
@vladrusu You around?

**Comment by vladrusu** [comment]
Hello !
Unfortunately, for brackets support I'll have to rework one or two things.... :-)

Give me several days, I'll try to do it.

**Comment by nanawel** [comment]
@vladrusu Any update on this?

**Pull request merged**
