### PR TITLE
Add support for standalone self-closing tags

### PR DESCRIPTION
**Pull request by cheryllium**

### CODE REVIEW

**Comment by cheryllium** [comment]
Issue #132 

@milesj 
How does this look? Any tests I should add? 
Feel free to make any edits as you see fit.

**Comment by cheryllium** [comment]
@milesj 
Sorry to bother, have you had a chance to look at this yet?

**Comment by milesj** [comment]
Sorry, forgot about this.

Your whitespace is wrong. Can you match the source files?

**Comment by cheryllium** [comment]
@milesj Thank you for your response. A friend helped me fix the whitespace - could you please take a look and see if it's good now? Thanks!

**Comment by milesj** [comment]
Looks good, thanks!

**Pull request merged**
