### PR TITLE
Add Script Tag

### PR DESCRIPTION
**Pull request by general03**
Allow to use script tag, for me it's for gist

### CODE REVIEW

**Comment by milesj** [comment]
What is the use case? This sounds like a major XSS/injection hole.

**Comment by general03** [comment]
Yes I'm agree with you but in Script tag it's not permit to put javascript content between tag, only link.
It's also security issue but I need to used Gist like that : [script src="https://gist.github.com/general03/793430d6f147382c5c39daba7f86df70"][/script]

**Comment by milesj** [comment]
It's still a massive vulnerability because you're linking to arbitrary scripts.

**Comment by general03** [comment]
Or I create a GistFilter and this allow to use only script from Github ?

**Pull request closed without merging**
